
import React from "react";

function Privacy() {
  return (
    <div className="min-h-screen bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-white p-8 md:p-12 shadow-lg rounded-lg">
        <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6 text-center">
          Privacy Policy & Terms
        </h1>
        <p className="text-sm text-gray-500 mb-10 text-center">
          Last updated: [Insert Date - e.g., October 26, 2023]
        </p>

        
        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4 border-b pb-2">
            Privacy Policy
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You. We use Your Personal data to provide and improve the
            Service. By using the Service, You agree to the collection and use
            of information in accordance with this Privacy Policy. This Privacy
            Policy has been created with the help of the Privacy Policy
            Generator.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
        </section>

        
        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4 border-b pb-2">
            Interpretation and Definitions
          </h2>
          <h3 className="text-xl font-semibold text-gray-700 mt-6 mb-3">
            Interpretation
          </h3>
          <p className="text-gray-700 leading-relaxed mb-4">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>
          <h3 className="text-xl font-semibold text-gray-700 mt-6 mb-3">
            Definitions
          </h3>
          <p className="text-gray-700 leading-relaxed mb-2">
            For the purposes of this Privacy Policy:
          </p>
          <ul className="list-disc pl-6 mb-4 text-gray-700 leading-relaxed space-y-2">
            <li>
              <strong>Account</strong> means a unique account created for You to
              access our Service or parts of our Service.
            </li>
            <li>
              <strong>Company</strong> (referred to as either "the Company",
              "We", "Us" or "Our" in this Agreement) refers to [Your Company
              Name], [Your Company Address].
            </li>
            <li>
              <strong>Cookies</strong> are small files that are placed on Your
              computer, mobile device or any other device by a website,
              containing the details of Your browsing history on that website
              among its many uses.
            </li>
            <li>
              <strong>Country</strong> refers to: [Your Country, e.g., India]
            </li>
            <li>
              <strong>Device</strong> means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to
              an identified or identifiable individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Website.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit).
            </li>
            <li>
              <strong>Website</strong> refers to [Your Website Name], accessible
              from [Your Website URL]
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </li>
          </ul>
        </section>

       
        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4 border-b pb-2">
            Collecting and Using Your Personal Data
          </h2>

          <h3 className="text-xl font-semibold text-gray-700 mt-6 mb-3">
            Types of Data Collected
          </h3>

          <h4 className="text-lg font-semibold text-gray-700 mt-4 mb-2">
            Personal Data
          </h4>
          <p className="text-gray-700 leading-relaxed mb-4">
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul className="list-disc pl-6 mb-4 text-gray-700 leading-relaxed space-y-1">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
            
          </ul>

          <h4 className="text-lg font-semibold text-gray-700 mt-6 mb-2">
            Usage Data
          </h4>
          <p className="text-gray-700 leading-relaxed mb-4">
            Usage Data is collected automatically when using the Service.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            Usage Data may include information such as Your Device's Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
            
          </p>
          

          <h3 className="text-xl font-semibold text-gray-700 mt-6 mb-3">
            Use of Your Personal Data
          </h3>
          <p className="text-gray-700 leading-relaxed mb-2">
            The Company may use Personal Data for the following purposes:
          </p>
          <ul className="list-disc pl-6 mb-4 text-gray-700 leading-relaxed space-y-2">
            <li>
              <strong>To provide and maintain our Service,</strong> including to
              monitor the usage of our Service.
            </li>
            <li>
              <strong>To manage Your Account:</strong> to manage Your
              registration as a user of the Service. The Personal Data You
              provide can give You access to different functionalities of the
              Service that are available to You as a registered user.
            </li>
            <li>
              <strong>For the performance of a contract:</strong> the
              development, compliance and undertaking of the purchase contract
              for the products, items or services You have purchased or of any
              other contract with Us through the Service.
            </li>
            <li>
              <strong>To contact You:</strong> To contact You by email,
              telephone calls, SMS, or other equivalent forms of electronic
              communication... [Elaborate on contact reasons]
            </li>
           
            <li>
              <strong>To manage Your requests:</strong> To attend and manage
              Your requests to Us.
            </li>
          </ul>
          
        </section>

        
        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4 border-b pb-2">
            Children’s Privacy
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            Our Service does not address anyone under the age of 13 [Adjust age
            based on regulations like GDPR/COPPA]. We do not knowingly collect
            personally identifiable information from anyone under the age of 13.
            If You are a parent or guardian and You are aware that Your child
            has provided Us with Personal Data, please contact Us. If We become
            aware that We have collected Personal Data from anyone under the age
            of 13 without verification of parental consent, We take steps to
            remove that information from Our servers.
          </p>
        </section>

        
        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4 border-b pb-2">
            Links to Other Websites
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            Our Service may contain links to other websites that are not
            operated by Us. If You click on a third party link, You will be
            directed to that third party's site. We strongly advise You to
            review the Privacy Policy of every site You visit.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </p>
        </section>

       
        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4 border-b pb-2">
            Changes to this Privacy Policy
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            We may update Our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            We will let You know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the "Last
            updated" date at the top of this Privacy Policy.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>
        </section>

        
        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4 border-b pb-2">
            Contact Us
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            If you have any questions about this Privacy Policy, You can contact
            us:
          </p>
          <ul className="list-disc pl-6 mb-4 text-gray-700 leading-relaxed space-y-2">
            <li>
              By email:{" "}
              <a
                href="mailto:[Your Contact Email]"
                className="text-blue-600 hover:underline"
              >
                [shivamahaur714@gmail.com]
              </a>
            </li>
            <li>
              By visiting this page on our website:{" "}
              <a
                href="[Link to Your Contact Page]"
                className="text-blue-600 hover:underline"
              >
                [Link to Your Contact Page]
              </a>
            </li>
            <li>By phone number: [9639753716]</li>
            <li>By mail: [Your Full Mailing Address]</li>
          </ul>
        </section>

        
        <hr className="my-10 border-gray-300" />

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4 border-b pb-2">
            Terms & Conditions – Customer Responsibility Clause
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            At Qooling, we are committed to providing professional and
            transparent AC services through our trusted team. However, please
            note:
            <hr /> ⚠️ If any customer pays additional charges directly to the
            technician, or hides service details from the company, Qooling will
            not be responsible for any service issues, damages, or warranty
            claims arising from such actions.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            Our company provides leads, manages service requests, and ensures
            quality through proper communication and billing. Any unauthorized
            transactions outside our system are not covered under our service
            guarantee or customer support. We request all customers to maintain
            transparency and only pay as per the bill provided by Qooling.<hr/>
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
          By email: shivamahaur714@gmail.com ||
          By phone number: 9639753716
          </p>
        </section>
      </div>
    </div>
  );
}

export default Privacy;
